spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/dev/ForStudyTestCode/SPRING/spring-mybatis-demo/test
      username: sa
      password: