spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://localhost/~/dev/ForStudyTestCode/ddd-start2-practice/shop
    url: jdbc:h2:tcp://localhost/C:/DEV-Studio/ForStudyTestCode/ddd-start2-practice/shop
    username: sa
    hikari:
      maximum-pool-size: 10

  jpa:
    database: h2
    show-sql: true
    open-in-view: false

logging:
  root: info
  com.myshop: debug
